### ISSUE TITLE
Verbose logger log level

### ISSUE THREAD

**Issue by JoseKilo** [NRWLDev/pytest-pogo#1]
Related to: https://github.com/NRWLDev/pogo-migrate/issues/9

This plugin could set a less verbose option by default, so that the migrating/rolling-back log entries aren't reported after each test failure.

It could also be configurable via a pytest plugin option, so that the level could be changed easily from the pytest command line.

**Comment by EdgyEdgemond** [comment]
pytest-pogo v0.0.4 extracts the verbosity level from the command line and uses that to set the verbosity of the fixture.

`pytest -v` will expose the previously verbose output.
