### ISSUE TITLE
Rollback migrations after a test failure

### ISSUE THREAD

**Issue by JoseKilo** [NRWLDev/pytest-pogo#2]
I think rollback should happen inside a `finally` block:

https://github.com/NRWLDev/pytest-pogo/blob/67c954fb4eebf477c7a8a450361f78951f8b701c/pytest_pogo/__init__.py#L21

That way migrations would get rolled back and re-applied for the next test as expected.

Otherwise when the fixture runs for the next test it will find the migrations already applied and won't do anything, leaking data from the failing test to the next one.

**Comment by EdgyEdgemond** [comment]
The migrations are handled in a session fixture that yields, this is handled at pytest level already. Test failures *should not* interfere with setup/teardown of migrations.
